export const VEHICLE_LOGIN_REQUEST = 'VEHICLE_LOGIN_REQUEST'
export const VEHICLE_LOGIN_SUCCESS = 'VEHICLE_LOGIN_SUCCESS'
export const VEHICLE_LOGIN_FAIL = 'VEHICLE_LOGIN_FAIL'

export const VEHICLE_LOGOUT = 'VEHICLE_LOGOUT'

export const VEHICLE_SIGNUP_REQUEST = 'VEHICLE_SIGNUP_REQUEST'
export const VEHICLE_SIGNUP_SUCCESS = 'VEHICLE_SIGNUP_SUCCESS'
export const VEHICLE_SIGNUP_FAIL = 'VEHICLE_SIGNUP_FAIL'

export const VEHICLE_PROFILE_REQUEST = 'VEHICLE_PROFILE_REQUEST'
export const VEHICLE_PROFILE_SUCCESS = 'VEHICLE_PROFILE_SUCCESS'
export const VEHICLE_PROFILE_FAIL = 'VEHICLE_PROFILE_FAIL'

export const GET_ALL_VEHICLES_REQUEST = 'GET_ALL_VEHICLES_REQUEST'
export const GET_ALL_VEHICLES_SUCCESS = 'GET_ALL_VEHICLES_SUCCESS'
export const GET_ALL_VEHICLES_FAIL = 'GET_ALL_VEHICLES_FAIL'

export const CROSS_VEHICLE_REQUEST = 'CROSS_VEHICLE_REQUEST'
export const CROSS_VEHICLE_SUCCESS = 'CROSS_VEHICLE_SUCCESS'
export const CROSS_VEHICLE_FAIL = 'CROSS_VEHICLE_FAIL'
export const CROSS_VEHICLE_RESET = 'CROSS_VEHICLE_RESET'

