export const GET_VIOLATION_TYPES_REQUEST = 'GET_VIOLATION_TYPES_REQUEST'
export const GET_VIOLATION_TYPES_SUCCESS = 'GET_VIOLATION_TYPES_SUCCESS'
export const GET_VIOLATION_TYPES_FAIL = 'GET_VIOLATION_TYPES_FAIL'

export const ADD_VIOLATION_TYPES_REQUEST = 'ADD_VIOLATION_TYPES_REQUEST'
export const ADD_VIOLATION_TYPES_SUCCESS = 'ADD_VIOLATION_TYPES_SUCCESS'
export const ADD_VIOLATION_TYPES_FAIL = 'ADD_VIOLATION_TYPES_FAIL'

export const EDIT_VIOLATION_TYPES_REQUEST = 'EDIT_VIOLATION_TYPES_REQUEST'
export const EDIT_VIOLATION_TYPES_SUCCESS = 'EDIT_VIOLATION_TYPES_SUCCESS'
export const EDIT_VIOLATION_TYPES_FAIL = 'EDIT_VIOLATION_TYPES_FAIL'

export const DELETE_VIOLATION_TYPES_REQUEST = 'DELETE_VIOLATION_TYPES_REQUEST'
export const DELETE_VIOLATION_TYPES_SUCCESS = 'DELETE_VIOLATION_TYPES_SUCCESS'
export const DELETE_VIOLATION_TYPES_FAIL = 'DELETE_VIOLATION_TYPES_FAIL'