export const CURRENT_VEHICLE_VIOLATIONS_REQUEST = 'CURRENT_VEHICLE_VIOLATIONS_REQUEST'
export const CURRENT_VEHICLE_VIOLATIONS_SUCCESS = 'CURRENT_VEHICLE_VIOLATIONS_SUCCESS'
export const CURRENT_VEHICLE_VIOLATIONS_FAIL = 'CURRENT_VEHICLE_VIOLATIONS_FAIL'

export const GET_VIOLATION_REQUEST = 'GET_VIOLATION_REQUEST'
export const GET_VIOLATION_SUCCESS = 'GET_VIOLATION_SUCCESS'
export const GET_VIOLATION_FAIL = 'GET_VIOLATION_FAIL'

export const PAY_VIOLATION_REQUEST = 'PAY_VIOLATION_REQUEST'
export const PAY_VIOLATION_SUCCESS = 'PAY_VIOLATION_SUCCESS'
export const PAY_VIOLATION_FAIL = 'PAY_VIOLATION_FAIL'

export const CREATE_VIOLATION_REQUEST = 'CREATE_VIOLATION_REQUEST'
export const CREATE_VIOLATION_SUCCESS = 'CREATE_VIOLATION_SUCCESS'
export const CREATE_VIOLATION_FAIL = 'CREATE_VIOLATION_FAIL'

export const FILTERS_VIOLATIONS_REQUEST = 'FILTERS_VIOLATIONS_REQUEST'
export const FILTERS_VIOLATIONS_SUCCESS = 'FILTERS_VIOLATIONS_SUCCESS'
export const FILTERS_VIOLATIONS_FAIL = 'FILTERS_VIOLATIONS_FAIL'

export const DELETE_VIOLATION_REQUEST = 'DELETE_VIOLATION_REQUEST'
export const DELETE_VIOLATION_SUCCESS = 'DELETE_VIOLATION_SUCCESS'
export const DELETE_VIOLATION_FAIL = 'DELETE_VIOLATION_FAIL'

export const EDIT_VIOLATION_REQUEST = 'EDIT_VIOLATION_REQUEST'
export const EDIT_VIOLATION_SUCCESS = 'EDIT_VIOLATION_SUCCESS'
export const EDIT_VIOLATION_FAIL = 'EDIT_VIOLATION_FAIL'